name:                t3
version:             0.1.0.0
github:              "thinkmpink/t3"
license:             BSD3
author:              "Michael Pinkham"
maintainer:          "mpinkham3@gmail.com"
copyright:           "Michael Pinkham 2017"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/thinkmpink/t3#readme>

dependencies:
- base >= 4.7 && < 5
- zippers >= 0.3
- containers >= 0.6
- vector >= 0.12

library:
  source-dirs: src

executables:
  t3-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - t3

tests:
  t3-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - t3
